[package]
name = "metar-taf-core"
version = "0.2.0-alpha4"
edition = "2024"
description = "METAR and TAF parsing library"
license = "MIT"

[dependencies]
thiserror = "2.0.17"
serde = { version = "1.0.228", features = ["derive"] }